### PR TITLE
Use Rich for displaying diffs in errors

### LINKED ISSUE #211: Rewrite diff code using Rich
The code in `diff.py` is pretty much the final location in Ward that isn't using Rich for terminal output. We should update it to use Rich, which should also allow us to more easily add test coverage around this area.

I've put this as a "Good First Issue" because the diff code is fairly de-coupled from the rest of Ward.

### PR DESCRIPTION
**Pull request by alanbato**
Fixes #211 using the suggestions provided there.

I rewrote the Diff coloring logic to use Rich instead of colorama and termcolor.

I took the liberty of refactoring a bit to make the code less complex, like reducing the number of if/elif statements  and intermediate variables that were not needed at the end :)

Let me know if you have any questions or you'd like me to make any changes 👍

### CODE REVIEW

**Comment by darrenburns** [comment]
Love this! Thanks! 🎉 

I've added some tests around it, since I think now is a perfect time to do it. I've also made a small change to the output (removed the bold and made it white text on the red/green backgrounds in the diff). I also made a small code change (`return` to `yield from`) to keep things a bit more consistent with the other places we use the Rich Console protocol).

I'll hopefully have the opportunity to have a closer look at the code over the next few days 🙂

**Comment by darrenburns** [comment]
I've added a bunch of tests around most of this, and I'm merging now, thanks again for this contribution @alanbato! :)

It also let me remove `termcolor` and `colorama` dependencies, since this was the only place left that wasn't using Rich.

**Comment by alanbato** [comment]
Awesome! Glad I could help, it was fun :)

Let me know if there's something else I can help with

**Comment by darrenburns** [comment]
Feel free to have a look at the open issues or discussions for inspiration, or if you have any ideas of your own let us know :)

**Pull request merged**
