### PR TITLE
Print pretty failure messages for `in` and `not in`

### LINKED ISSUE #240: No pretty failure message for `in` statements
Working on tests for #233 and noticed that `in` statements don't seem to be getting rewritten to produce pretty output. Minimal example:
```python
@test("assert in not working?")
def _():
    assert "foo" in "bar"
```

```
─────────────────────────────────────────────── assert in not working? ───────────────────────────────────────────────

  Failed at tests/test_terminal.py:300

      298 @test("assert in not working?")
      299 def _():
    ❱ 300     assert "foo" in "bar"
      301

──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

### PR DESCRIPTION
**Pull request by JoshKarpel**
resolves #240 ; this PR adds a case for the `in` and `not in` operators. This is what it looks like in action:

image

### CODE REVIEW

**Comment by darrenburns** [comment]
Been playing around with the output here. Can't decide whether I like the panels though since they're a bit inconsistent with the `assert ==` diff failure output. 

Using `expand_all=True` in the `Pretty` also seems to make lists render with a single element on each line, even if the elements are just simple types like `int`:

image

With `expand_all=False`:
image

**Comment by JoshKarpel** [comment]
I like how you've got it looking now, with the text in the panel titles! I think what's interesting about the panels is that it clearly delineates the framework output from the objects under test, so I'd be in favor of keeping them.

Agreed on not setting `expand_all` - I was hoping it would make it easier to spot differences, but that falls apart if the container is large. We'd need the custom highlighting to make that really smooth, as you mentioned.

Also agreed on the inconsistency in the design. Not sure how to approach that. I was thinking of building a few more of these for other operators soon - perhaps we build a few more and then try to factor the designs together once we know what we're working with?

**Comment by darrenburns** [comment]
Cool, I've pushed up the changes for that approach then.

> Also agreed on the inconsistency in the design. Not sure how to approach that. I was thinking of building a few more of these for other operators soon - perhaps we build a few more and then try to factor the designs together once we know what we're working with?

Yeah, I'm happy with that approach. I think it's good to be exploratory at this stage and just see what works!

**Comment by JoshKarpel** [comment]
I did some cleanup of the API and merged master to pick up the changes from #235 . Ready for another review.

**Comment by darrenburns** [comment]
Added a few tests and made it so we pass the `Console` into the result writer rather than using the global instance directly. This will hopefully make testing easier later since we'll be able to pass in a mock console and check we interact with it correctly.  Trying to not go too detailed with testing specific output to give us the ability to refine and iterate on it, but would still like the code to be "exercised" to some extent.

**Comment by darrenburns** [comment]
Merging this now, thanks again 🎉 😄

**Comment by JoshKarpel** [comment]
Nice tests! I also like passing the console explicitly.

**Pull request merged**
