### PR TITLE
Add Python 3.10 Beta support to CI

### PR DESCRIPTION
**Pull request by Catastrophe0123**
#228

### CODE REVIEW

**Comment by darrenburns** [comment]
Hmm, bumping `snok/install-poetry` up to v1.1.6 (it's currently 1.1.1) might fix it?

**Comment by Catastrophe0123** [comment]
I think it should. Check this https://github.com/python-poetry/poetry/issues/4056#issuecomment-846602490

**Comment by darrenburns** [comment]
Good find 🙂 feel free to add that to this PR. If you can't I'll update it tomorrow.

**Comment by Catastrophe0123** [comment]
@darrenburns, The tests are passing

**Comment by darrenburns** [comment]
Great work, thank you for this! 👏

**Pull request merged**
