### PR TITLE
ditch the setup.py for a flit-flavored pyproject.toml

### PR DESCRIPTION
**Pull request by AndydeCleyre**
If you're interested in switching from `setup.py` to `pyproject.toml` (with `flit`), take a look. I thought this might be a good step toward #68.

Notes:
- `flit` looks for a project description at the start of `__init__.py`, so I moved it there
- I added a `dev-requirements.txt` though I don't know if you want that
- Someone with Windows would have to test if a workaround is still necessary here ("Work around encoding errors when installing on Windows." from `setup.py`)
- I don't know if you want to relax the dev dependency versions, if you want to keep them at all

### CODE REVIEW

**Comment by darrenburns** [comment]
Thank you for this! It looks much nicer for sure 🎉  I'm actually working on the `pyproject.toml` stuff just now!

I was actually considering migrating stuff over to use Poetry rather than Flit, but I haven't used either of them extensively in the past. Have you tried both? If so, any reason you prefer Flit?

**Comment by darrenburns** [comment]
Also, the encoding errors I experienced with setup.py on Windows were appearing in the CI, which includes Windows tests. It seems this may have also fixed that issue :)

**Comment by AndydeCleyre** [comment]
I prefer flit because it's a tool for distributing to PyPI, and not a tool for other things, for which I'd prefer to choose other, task-focused tools (like `pip-tools` for dependency management). 

Poetry does *a lot*; it's got its own dependency resolver, venv/shell management, dependency tracking, etc. I'm not a fan of its use of `poetry.lock`, when `requirements.txt` is already suitable as a lockfile, and `pip-tools` does great using `requirements.in` as a "loose" file (without new syntax) to be processed into `requirements.txt`. I don't know if you intend to use Poetry for all those tasks.

I prefer using `requirements.{in,txt}` files to `toml` files for dependency listing, as they lend themselves better to manipulation with shell tools. I use a script to (re)populate the `pyproject.toml` requirements based on the content of those text files (if curious, check the `pypc` function in my github project `zpy`).

Everybody loves Poetry and it's a great project, and if you like it for Ward I don't have anything to say against it.

**Comment by darrenburns** [comment]
Interesting, thanks for the info. I really like this and plan to merge it. However, the GitHub Action for releasing will have to be updated first since it still builds with setuptools etc.

**Comment by AndydeCleyre** [comment]
I'm not totally sure about the workflow (where is `__token__` defined -- outside the codebase, on github servers? Would you rather use latest `flit`, or install everything in `dev-requirements.txt`?)

But I'll add a commit here which should be close to working, if not working.

**Comment by darrenburns** [comment]
`__token__` is just a way of telling PyPI that the `password` field refers to an API token, rather than an actual password. It isn't a variable or anything.

> To use an API token:
> 
>     Set your username to __token__
>     Set your password to the token value, including the pypi- prefix
> 

(from https://pypi.org/help/#apitoken)

I don't mind using the latest flit rather than installing dev-reqs.

`$GITHUB_WORKSPACE` is not the default working dir afaik. You can use the `working-directory` keyword to execute a command in a specific directory: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobsjob_idstepsrun

**Comment by AndydeCleyre** [comment]
Alright, can you take a look at the current state and (most likely) fix up the workflow(s)?

**Comment by darrenburns** [comment]
Yeah, we could just bin dev-requirements

**Pull request merged**
