### PR TITLE
Allow path to refer to normal files

### LINKED ISSUE #84: --path expects a directory, doesnt work with a path to a file
If you pass a path to a file, e.g.: `ward --tests/test_something.py`, Ward won't find any tests. The command line API is defined in `run.py`, and the actual collection of modules and tests happens in `collect.py`.

### PR DESCRIPTION
**Pull request by onlyanegg**
Fixes #84 

- Added work around for normal files passed in through --path
- Changed to using walk_packages for recursive search

### CODE REVIEW

**Comment by onlyanegg** [comment]
@darrenburns , I looked through pkgutil and couldn't find anything that operated on normal files. I tracked it down to the FileFinder import hook which doesn't accept files, and I stopped there, because I'm scared of the import system.

Instead, for all normal files passed through --path, I'm iterating over their parent directories and checking if they match the file name. I also  removed the recursive code and replaced it with `pkgutil.walk_packages`, because I'm fairly sure it does the same thing. Finally, I removed the os import, since it wasn't being used.

**Comment by darrenburns** [comment]
Heh, you just beat me to it. I just opened a PR for the same issue at #110 😄 might be interesting to compare approaches and see if we can get the best of both worlds!

Thanks for this, I'll take a look at it soon!

**Comment by onlyanegg** [comment]
Oh, dang. I was worried about that. I tend to avoid saying claiming the issue, in case I end up not finishing it.

**Comment by darrenburns** [comment]
Don't worry about it 😄 FWIW, I think the `walk_packages` approach you've taken looks much cleaner and would like to see that integrated. An issue I've found in this PR is that it doesn't behave as I'd expect for the following example (when running Ward's own test suite):

```
ward --path tests --path tests/test_collect.py
```

Since `test_collect.py` is contained within `tests`, the tests in that module get executed twice. I would expect `test_collect.py` to only be executed once.

**Comment by onlyanegg** [comment]
For sure. I saw that you handled that case in your PR. Let me know what you'd like to do. I wont be bothered either way.

**Comment by darrenburns** [comment]
I've spent some time investigating and unfortunately I don't think there's a way to integrate your approach. Using `walk_packages` would impose an additional requirement on users that their test directories all contain `__init__.py` files.

Sorry about that -- I've added you to the contributors list in my PR regardless -- and hope this doesn't put you off contributing again! :)

**Comment by onlyanegg** [comment]
Actually, I'm not seeing that behavior on my end. I can run `ward --path tests/` from the root directory with no problems.

**Comment by darrenburns** [comment]
@onlyanegg If you run `ward --path .` you should see what I mean, or create a subdirectory in the `tests/` containing another test module and run `ward --path tests`.

**Comment by onlyanegg** [comment]
Oh, yeah, I see that now. No worries, and you don't have to apologize. That's something that I should have checked before submitting.

**Pull request closed without merging**
